version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "chore(deps): " for conventional commit messages
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    groups:
      dependencies:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"
        patterns:
        - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha:
        applies-to: version-updates
        patterns:
        - "*"
